# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "scholar"
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=NBH8onQAAAAJ"

[social.params]
icon = "brand-scholar"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Sebo-the-tramp"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/sebastiancavada/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://mobile.twitter.com/_cavada"

[social.params]
icon = "brand-twitter"


